# SPDX-FileCopyrightText: 2026 Bart van de Lint
# SPDX-License-Identifier: MIT

# DO NOT EDIT THIS FILE
# This file was generated by src/build.jl
# Edit src/awesio/structure_schema.yml instead

"""
    DynamicsType

The dynamic model governing a component. DYNAMIC components carry differential state and are
solved by the dynamics; the others are prescribed, holding no state but mutable between
steps.
"""
@enum DynamicsType DYNAMIC STATIC BODY_STATIC KINEMATIC

"""
    Metadata

The `metadata` block of a structure document.

- `name::String`
- `description::String`
- `note::String`
- `awesIO_version::String`: Version of this schema the file was written against.
- `schema::String`
- `n_points::Int`: Number of rows in the points block.
- `connectivity_sha::String`: Lowercase hex SHA-256 of the connectivity, so state recorded
  against one structure is not silently replayed against another that indexes differently.
  The preimage is ASCII and built in document order, in two sections: the number of points,
  then each segment's two endpoints as ONE-BASED row numbers into the points block; then the
  number of bodies, then each tube's two bodies as one-based row numbers into the bodies
  block. The two numbers of a pair are comma-separated and every field ends in a semicolon,
  so a lone number always opens a section. Three points joined in a row, on two bodies
  joined by one tube, read `3;1,2;2,3;2;1,2;`. Row numbers are one-based so that
  implementations in zero-based languages agree with each other; a reader that gets this
  wrong sees every file as a mismatch.
"""
struct Metadata
    name::String
    description::String
    note::String
    awesIO_version::String
    schema::String
    n_points::Int
    connectivity_sha::String
end

"""
    Point

A row of the `points` block. Mass points.

- `name::String`: Unique name of the point. A writer whose geometry is index-keyed writes
  the index as a string, "1" upwards.
- `type::DynamicsType`: STATIC: fixed in the world. DYNAMIC: free, moved by the forces on
  it. BODY_STATIC: fixed in the frame of the rigid body `body` names, moving with it and
  passing its force and moment on to it.
- `body::Union{Nothing, NameRef}`: The rigid body a BODY_STATIC point is fixed to; null for
  any other point.
- `pos_ENU::SVector{3, Float64}`: Position [m] in the world.
- `extra_mass::Float64`: Mass [kg] the point carries beyond its segments.
- `drag_area::Float64`: Cross-sectional area [m²] the point's drag acts on.
- `drag_coefficient::Float64`: Drag coefficient [-] referred to `drag_area`.
- `extras::OrderedDict{String, Any}`: columns the schema does not name, in the order read
"""
struct Point <: Component
    name::String
    type::DynamicsType
    body::Union{Nothing, NameRef}
    pos_ENU::SVector{3, Float64}
    extra_mass::Float64
    drag_area::Float64
    drag_coefficient::Float64
    extras::OrderedDict{String, Any}
end

"""
    Segment

A row of the `segments` block. Straight elastic elements between two points.

- `name::String`: Unique name of the segment.
- `points::NTuple{2, NameRef}`: The two points the segment joins.
- `l0::Float64`: Unstretched length [m].
- `diameter::Float64`: Diameter [m] of the line, for its mass and drag.
- `density::Float64`: Density [kg/m³] of the line's material.
- `unit_stiffness::Union{Float64, String}`: Axial stiffness times unstretched length [N], or
  the name of a nonlinear law.
- `extras::OrderedDict{String, Any}`: columns the schema does not name, in the order read
"""
struct Segment <: Component
    name::String
    points::NTuple{2, NameRef}
    l0::Float64
    diameter::Float64
    density::Float64
    unit_stiffness::Union{Float64, String}
    extras::OrderedDict{String, Any}
end

"""
    Station

A row of the `stations` block. Chordwise sections of a wing. A station's points give the
local chord, from which a reader derives the section's angle of attack and, where the points
trace the profile, its airfoil shape; the aerodynamic load of the span the station covers is
put onto those points. A station's local twist is the angle its chord has turned through
about the wing's KA y axis from where the document places it, positive pitching the leading
edge up. A station is not tied to the aerodynamic mesh. Rows run from +y to -y of the wing's
KA frame.

- `name::String`: Unique name of the station.
- `type::DynamicsType`: DYNAMIC: the twist is a state, solved from the moments on the
  station. STATIC: the twist is a prescribed control input. KINEMATIC: the twist is
  prescribed by geometry, such as a flap hinged between two bodies.
- `points::Vector{NameRef}`: The points the section is made of.
- `extras::OrderedDict{String, Any}`: columns the schema does not name, in the order read
"""
struct Station <: Component
    name::String
    type::DynamicsType
    points::Vector{NameRef}
    extras::OrderedDict{String, Any}
end

"""
    Pulley

A row of the `pulleys` block.

- `name::String`: Unique name of the pulley.
- `segments::NTuple{2, NameRef}`: The two segments the pulley trades length between.
- `type::DynamicsType`: DYNAMIC: how the length is split between the two segments is a
  state.
- `efficiency::Float64`: Fraction [-] of the line tension the pulley passes on; the rest
  opposes travel.
- `extras::OrderedDict{String, Any}`: columns the schema does not name, in the order read
"""
struct Pulley <: Component
    name::String
    segments::NTuple{2, NameRef}
    type::DynamicsType
    efficiency::Float64
    extras::OrderedDict{String, Any}
end

"""
    Tether

A row of the `tethers` block. Ordered runs of segments between two points. Material lives on
the segments; a tether is the grouping a winch reels, and the length it is reeled from is
its segments' `l0`.

- `name::String`: Unique name of the tether.
- `start_point::NameRef`: The point the tether starts at.
- `end_point::NameRef`: The point the tether ends at.
- `segments::Vector{NameRef}`: The tether's segments, in order from `start_point` to
  `end_point`.
- `extras::OrderedDict{String, Any}`: columns the schema does not name, in the order read
"""
struct Tether <: Component
    name::String
    start_point::NameRef
    end_point::NameRef
    segments::Vector{NameRef}
    extras::OrderedDict{String, Any}
end

"""
    Winch

A row of the `winches` block.

- `name::String`: Unique name of the winch.
- `tethers::Vector{NameRef}`: The tethers the winch reels together.
- `winch_point::NameRef`: The point the drum sits at.
- `gear_ratio::Float64`: Gear ratio [-] of the drive to the drum.
- `drum_radius::Float64`: Radius [m] of the drum.
- `extras::OrderedDict{String, Any}`: columns the schema does not name, in the order read
"""
struct Winch <: Component
    name::String
    tethers::Vector{NameRef}
    winch_point::NameRef
    gear_ratio::Float64
    drum_radius::Float64
    extras::OrderedDict{String, Any}
end

"""
    Body

A row of the `bodies` block. Rigid bodies. A body's KA frame is oriented as
docs/source/conventions.rst defines `_KA` where the body has wing geometry, and as its
writer likes where it has no leading edge.

- `name::String`: Unique name of the body.
- `type::DynamicsType`: DYNAMIC: free in six degrees of freedom. KINEMATIC: its pose is
  fitted to its points. STATIC: clamped to the world.
- `pos_ENU::SVector{3, Float64}`: The body's origin, the centre of its own mass [m], in the
  world.
- `Q_KA_to_ENU::SVector{4, Float64}`: Rotation from the body's KA frame into the world.
- `extra_mass::Float64`: Mass [kg] the body carries beyond the points fixed to it.
- `extra_inertia_KA::SMatrix{3, 3, Float64, 9}`: Inertia tensor [kg·m²] of `extra_mass`
  about the body's origin, in its KA axes. Principal moments are the case where the KA axes
  are the principal axes and the tensor is diagonal; a tool that carries no rotational
  inertia writes zeros.
- `extras::OrderedDict{String, Any}`: columns the schema does not name, in the order read
"""
struct Body <: Component
    name::String
    type::DynamicsType
    pos_ENU::SVector{3, Float64}
    Q_KA_to_ENU::SVector{4, Float64}
    extra_mass::Float64
    extra_inertia_KA::SMatrix{3, 3, Float64, 9}
    extras::OrderedDict{String, Any}
end

"""
    Tube{M}

A row of the `tubes` block. Inflated beam elements between two bodies, whose positions fix
the element's ends and so its rest length. How it curves between those ends belongs to the
element: only a shape its `law` cannot hold, or a taper, is a chain of tubes.

- `name::String`: Unique name of the tube.
- `bodies::NTuple{2, NameRef}`: The two bodies whose positions fix the tube's ends.
- `diameter::Float64`: Diameter [m], one for the whole element.
- `pressure::Float64`: Inflation pressure [Pa].
- `law::String`: The stiffness law the element's rigidities are derived from.
- `extras::OrderedDict{String, Any}`: columns the schema does not name, in the order read
"""
struct Tube{M <: AbstractTubeModel} <: Component
    name::String
    bodies::NTuple{2, NameRef}
    diameter::Float64
    pressure::Float64
    law::String
    extras::OrderedDict{String, Any}
end

"""
    SystemDefinition

A structure document: its metadata, one vector per table block, and the blocks the schema
does not name.

- `metadata::Metadata`: the document's metadata
- `points::Vector{Point}`: the rows of `points`
- `segments::Vector{Segment}`: the rows of `segments`
- `stations::Vector{Station}`: the rows of `stations`
- `pulleys::Vector{Pulley}`: the rows of `pulleys`
- `tethers::Vector{Tether}`: the rows of `tethers`
- `winches::Vector{Winch}`: the rows of `winches`
- `bodies::Vector{Body}`: the rows of `bodies`
- `tubes::Vector{Tube}`: the rows of `tubes`
- `extras::OrderedDict{String, Any}`: blocks the schema does not name, in the order read
"""
struct SystemDefinition
    metadata::Metadata
    points::Vector{Point}
    segments::Vector{Segment}
    stations::Vector{Station}
    pulleys::Vector{Pulley}
    tethers::Vector{Tether}
    winches::Vector{Winch}
    bodies::Vector{Body}
    tubes::Vector{Tube}
    extras::OrderedDict{String, Any}
end

"""The component type of each table block, in schema order."""
const BLOCKS = (
    points = Point,
    segments = Segment,
    stations = Station,
    pulleys = Pulley,
    tethers = Tether,
    winches = Winch,
    bodies = Body,
    tubes = Tube,
)

"""The blocks a structure document must carry."""
const REQUIRED_BLOCKS = (:metadata, :points, :segments)
