# SPDX-FileCopyrightText: 2026 Bart van de Lint
# SPDX-License-Identifier: MIT

# Writes src/_structure.jl, the component types of KiteGeometry, from the vendored awesIO
# schema src/awesio/structure_schema.yml. Run with `julia --project src/build.jl`.
using YAML, OrderedCollections

SCHEMA = joinpath(@__DIR__, "awesio", "structure_schema.yml")
OUTPUT = joinpath(@__DIR__, "_structure.jl")
WIDTH = 92

HEADER = """
# SPDX-FileCopyrightText: 2026 Bart van de Lint
# SPDX-License-Identifier: MIT

# DO NOT EDIT THIS FILE
# This file was generated by src/build.jl
# Edit src/awesio/structure_schema.yml instead
"""

COLUMN_TYPES = Dict(
    "component_name" => "NameRef",
    "optional_name" => "Union{Nothing, NameRef}",
    "name_pair" => "NTuple{2, NameRef}",
    "name_list" => "Vector{NameRef}",
    "vec3" => "SVector{3, Float64}",
    "matrix3" => "SMatrix{3, 3, Float64, 9}",
    "quaternion" => "SVector{4, Float64}",
    "length" => "Float64",
    "density" => "Float64",
    "non_negative" => "Float64",
    "fraction" => "Float64",
    "rigidity" => "Union{Float64, String}",
    "model_name" => "String",
    "dynamics_type" => "DynamicsType",
)
METADATA_TYPES = Dict("string" => "String", "integer" => "Int")
MODEL_PARAMETERS = Dict("tubes" => "M <: AbstractTubeModel")

"""Julia type name of the rows of `block`: `bodies` gives `Body`, `winches` `Winch`."""
function type_name(block)
    singular = endswith(block, "ies") ? block[1:(end - 3)] * "y" :
               endswith(block, "ches") ? block[1:(end - 2)] : block[1:(end - 1)]
    return uppercasefirst(singular)
end

"""`text` re-flowed into lines of at most `WIDTH - indent` characters."""
function wrap(text, indent=0)
    lines = String[]
    line = ""
    for word in split(strip(text))
        if !isempty(line) && length(line) + 1 + length(word) > WIDTH - indent
            push!(lines, line)
            line = ""
        end
        line = isempty(line) ? String(word) : line * " " * word
    end
    isempty(line) || push!(lines, line)
    return join(lines, "\n")
end

"""Docstring of a type: its signature, its description and one bullet per field."""
function docstring(signature, description, fields)
    bullets = String[]
    for (name, type, text) in fields
        bullet = isempty(text) ? "`$name::$type`" : "`$name::$type`: " * strip(text)
        push!(bullets, "- " * replace(wrap(bullet, 2), "\n" => "\n  "))
    end
    return "\"\"\"\n    $signature\n\n$(wrap(description))\n\n" *
           "$(join(bullets, "\n"))\n\"\"\"\n"
end

"""Definition name a `data` item refers to, from its `\$ref`."""
definition(item) = last(split(item["\$ref"], "/"))

"""`(header, Julia type, description)` of every required column of `block`."""
function columns(block, spec)
    parts = filter(part -> haskey(part, "properties"), spec["allOf"])
    length(parts) == 1 || error("block $block has no single allOf entry with properties")
    table = only(parts)["properties"]
    headers = table["headers"]["items"]
    items = table["data"]["items"]["items"]
    fields = Tuple{String, String, String}[]
    for (header, item) in zip(headers, items)
        name = header["const"]
        type = name == "name" ? "String" : COLUMN_TYPES[definition(item)]
        push!(fields, (name, type, header["description"]))
    end
    return fields
end

"""Source of the struct holding one row of `block`."""
function component_source(block, spec)
    fields = columns(block, spec)
    push!(fields, ("extras", "OrderedDict{String, Any}",
                   "columns the schema does not name, in the order read"))
    name = type_name(block)
    signature = haskey(MODEL_PARAMETERS, block) ? "$name{M}" : name
    head = haskey(MODEL_PARAMETERS, block) ? "$name{$(MODEL_PARAMETERS[block])}" : name
    description = "A row of the `$block` block. " * get(spec, "description", "")
    body = join(("    $field::$type" for (field, type, _) in fields), "\n")
    return docstring(signature, description, fields) *
           "struct $head <: Component\n$body\nend\n"
end

"""Source of `Metadata`, from the schema's `metadata` object."""
function metadata_source(spec)
    fields = Tuple{String, String, String}[]
    for name in spec["required"]
        property = spec["properties"][name]
        type = METADATA_TYPES[property["type"]]
        push!(fields, (name, type, get(property, "description", "")))
    end
    body = join(("    $field::$type" for (field, type, _) in fields), "\n")
    return docstring("Metadata", "The `metadata` block of a structure document.", fields) *
           "struct Metadata\n$body\nend\n"
end

"""Source of `DynamicsType`, from the schema's `dynamics_type` definition."""
function enum_source(spec)
    values = join(spec["enum"], " ")
    return "\"\"\"\n    DynamicsType\n\n$(wrap(spec["description"]))\n\"\"\"\n" *
           "@enum DynamicsType $values\n"
end

"""Source of `SystemDefinition`, one vector per table block, and of `BLOCKS`."""
function system_source(schema, blocks)
    fields = [("metadata", "Metadata", "the document's metadata")]
    for (block, _) in blocks
        push!(fields, (block, "Vector{$(type_name(block))}", "the rows of `$block`"))
    end
    push!(fields, ("extras", "OrderedDict{String, Any}",
                   "blocks the schema does not name, in the order read"))
    body = join(("    $field::$type" for (field, type, _) in fields), "\n")
    table = join(("    $block = $(type_name(block)),\n" for (block, _) in blocks))
    required = join((":$block" for block in schema["required"]), ", ")
    description = "A structure document: its metadata, one vector per table block, and " *
                  "the blocks the schema does not name."
    return docstring("SystemDefinition", description, fields) *
           "struct SystemDefinition\n$body\nend\n\n" *
           "\"\"\"The component type of each table block, in schema order.\"\"\"\n" *
           "const BLOCKS = (\n$table)\n\n" *
           "\"\"\"The blocks a structure document must carry.\"\"\"\n" *
           "const REQUIRED_BLOCKS = ($required)\n"
end

"""The source of `_structure.jl` for `schema`."""
function structure_source(schema)
    properties = schema["properties"]
    blocks = [(name, spec) for (name, spec) in properties if name != "metadata"]
    parts = [HEADER, enum_source(schema["definitions"]["dynamics_type"]),
             metadata_source(properties["metadata"]),
             (component_source(block, spec) for (block, spec) in blocks)...,
             system_source(schema, blocks)]
    return join(parts, "\n")
end

schema = YAML.load_file(SCHEMA; dicttype=OrderedDict{String, Any})
write(OUTPUT, structure_source(schema))
